import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const CreateMigraineWizard = () => {

  const { user } = useUser();

  if(!user) return null;

  return (
    <div className="flex gap-3 w-full">
      <img 
        src={user.profileImageUrl}
        alt="Profile Image"
        className="w-14 h-14 rounded-full"
      />
      <input 
        placeholder="Enter some Content" 
        className="grow bg-transparent outline-none"
      />
    </div>

  )
}

const Home: NextPage = () => {
  const user = useUser();

  const { data,isLoading } = api.migraines.getAll.useQuery();

  if(isLoading) return <div>Loading...</div>
  if(!data) return <div>No data yet...</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="flex border-b border-slate-400 p-4">
          {!user.isSignedIn && (
            <div className="flex justify-center">
              <SignInButton />
            </div>
          )}
          {!!user.isSignedIn && (
            <div className="flex justify-center">
              <CreateMigraineWizard />
              <SignOutButton />
            </div>
          )}
        </div>
        <div className="flex flex-col">
          {[...data, ...data]?.map((migraine, user) => (
            <div key={migraine.migraine.id} className="border-b border-slate-400 p-8">
              {migraine.migraine.content}
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
